config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get '/projects/:project_id/gitlab', to: 'git_lab_repositories#index', as: 'git_lab'
delete '/projects/:project_id/gitlab/:id', to: 'git_lab_repositories#destroy', as: 'git_lab_repository_destroy'
post '/projects/:project_id/gitlab', to: 'git_lab_repositories#create', as: 'git_lab_repository_create'

app/models/git_lab_repository.rb
class GitLabRepository < ActiveRecord::Base
  unloadable
  extend GitlabInt::GitlabMethods

  belongs_to :project
  belongs_to :user # Author

  validates :url, presence: true

  before_destroy :destroy_repository
  attr_accessible :description, :title, :url, :gitlab_id, :user_id, :project_id

  def build(attrs)
    case attrs[:context]
    when :add
      add_gitlab_repository(attrs)
    when :create
      create_gitlab_repository(attrs)
    end
  end

  private

  def destroy_repository
    self.class.gitlab_destroy({ token: User.current.gitlab_token, id: self.gitlab_id }) if autoremove_enabled?
  end

  def autoremove_enabled?
    self.gitlab_id && Setting.plugin_redmine_gitlab_integration['gitlab_autoremove'] == "enabled"
  end

  def add_gitlab_repository(attrs)
    assign_attributes({
                        title:       attrs[:title],
                        url:         attrs[:repository_url],
                        user_id:     attrs[:user_id],
                        project_id:  attrs[:project_id]
                      })
    self
  end

  def create_gitlab_repository(attrs)
    create_gitlab_group(attrs) unless attrs[:group] # project new or has no repositories
    glp = self.class.gitlab_create(attrs) # create repository in gitlab
    if glp.present? # So if we didn't create repository properly then url field would be nil and .save return false because of validation
      assign_attributes({
                          description: attrs[:description],
                          title:       attrs[:title],
                          url:         glp.http_url_to_repo,
                          gitlab_id:   glp.id,
                          user_id:     attrs[:user_id],
                          project_id:  attrs[:project_id]
                        })
    end
    self
  end

  def create_gitlab_group(attrs)
    attrs[:group], attrs[:op] = self.class.gitlab_create_group(attrs).id, :add
    self.class.gitlab_member(attrs) # add project owner to group
    set_gitlab_group(attrs)
  end

  def set_gitlab_group(attrs)
    project = Project.find(attrs[:project_id])
    project.update_attributes({ gitlab_group: attrs[:group] })
    members = project.members.map { |m| { token: m.user.gitlab_token, role: m.roles.first.id } }
    self.class.gitlab_add_members({ group: attrs[:group], members: members })
  end
end

app/controllers/git_lab_repositories_controller.rb
class GitLabRepositoriesController < ApplicationController
  unloadable
  before_filter :set_project, only: [:index, :destroy, :create]
  before_filter :set_repository, only: [:destroy]

  def index
    @repositories = @project.git_lab_repositories
  end

  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to git_lab_path(params[:project_id]) }
      format.json { head :no_content }
    end
  end

  def create
    ext_hash = params[:repository_url]  ? { context: :add }
                                        : { project_id: @project.id,
                                            identifier: @project.identifier,
                                            group: @project.gitlab_group,
                                            context: :create,
                                            user_id: User.current.id }
    begin
      @repository = GitLabRepository.new.build(params.merge(ext_hash)) # set attributes and optionally create repository in gitlab
    rescue
    end
    respond_to do |format|
      if @repository.save
        format.html { redirect_to git_lab_url(@project.id), notice: t(:gitlab_create_success) }
      else
        format.html { redirect_to git_lab_url(@project.id), alert: t(:gitlab_create_error) }
      end
    end
  end

  private
  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_repository
    @repository = GitLabRepository.find(params[:id])
  end
end

app/helpers/git_lab_repositories_helper.rb
module GitLabRepositoriesHelper
  def ssh_url(url)
    url.gsub(/https?\:\/\//, "git@")
  end

  def btn_id(type, id)
    "#{type}_btn_#{id}"
  end

  def project_clone_id(id)
    "project_clone_#{id}"
  end

  def user_has_token?
    User.current.gitlab_token && !User.current.gitlab_token.empty?
  end

  def user_allowed_to_add?
    User.current.allowed_to?(:add_new_repositories, @project)
  end

  def show_description(repo)
    if !repo.description || repo.description.empty?
      "No description."
    else
      "#{repo.description}..."
    end
  end
end

app/views/git_lab_repositories/_add_repository.html.erb
<%= form_tag git_lab_repository_create_path(project), class: "add-repository-form" do %>
  <fieldset class="box tabular"><legend><%= t(:gitlab_project_legend) %></legend>
  <p>
    <%= label_tag :repository_url, t(:field_name) %>
    <%= text_field_tag :title, "#{@project.identifier}_", required: true, size: 60 %>
  </p>
  <p>
    <%= label_tag :repository_url, "URL" %>
    <%= text_field_tag :repository_url, '', placeholder: 'https://gitlab.com/user/repository.git', required: true,  size: 60 %>
  </p>
  </fieldset>
  <input type="submit" class="approve-btn" value=<%= t(:button_add) %>>
  <input type="submit" class="close-btn" value=<%= t(:button_cancel) %>>
<% end %>

app/views/git_lab_repositories/_create_repository.html.erb
<%= form_tag git_lab_repository_create_path(project), { id: 'form-gitlab-create' } do %>
  <fieldset class="box tabular"><legend><%= t(:gitlab_project_legend) %></legend>
  <p>
    <%= label_tag :title, t(:field_name) %>
    <%= text_field_tag :title, "#{@project.identifier}_", size: 60 %>
  </p>
  <p>
    <%= label_tag :description, t(:field_description) %>
    <%= text_area_tag :description, '',  rows: 4, class: 'gitlab-textarea' %>
  </p>
  <p>
    <%= label_tag :visibility, t(:visibility_public) %>
    <%= check_box_tag 'visibility' %>
  </p>
  </fieldset>
  <input type="submit" class="approve-btn" value=<%= t(:button_create) %>>
  <input type="submit" class="close-btn" value=<%= t(:button_cancel) %>>
<% end %>

app/views/git_lab_repositories/_gitlab.html.erb
<% if ['new', 'create'].include? controller.action_name %>
  <p><%= label_tag 'project[gitlab_create]', t(:gitlab_repository_checkbox) %><%= check_box_tag 'project[gitlab_create]', 'true', false %></p>
  <fieldset class="box tabular" id="gitlab-fieldset"><legend><%= t(:gitlab_project_legend) %></legend>
  <p><%= label_tag 'project[gitlab_name]', t(:field_name) %><%= text_field_tag 'project[gitlab_name]', '', size: 60 %></p>
  <p><%= label_tag 'project[gitlab_description]', t(:field_description) %><%= text_area_tag 'project[gitlab_description]', '',  rows: 8 %></p>
  </fieldset>
<% end %>

app/views/git_lab_repositories/_repository.html.erb
<div class="box">
<div class="repository-header">
<h3 class="repository-title">
  <%= link_to repository.title, repository.url, target: '_blank' %>
</h3>
<%= link_to t(:gitlab_remove), git_lab_repository_destroy_path(project, repository.id), data: { confirm: t(:gitlab_confirm) }, method: :delete, class: "icon icon-del repository-remove" %>
</div>
<div class='git-holder'>
    <button class='url-btn ssh-btn active' id='<%= btn_id("ssh", repository.id) %>' data-clone='<%= ssh_url(repository.url) %>'>SSH</button>
    <button class='url-btn http-btn' id='<%= btn_id("http", repository.id) %>' data-clone='<%= repository.url %>'>HTTP</button>
  <input class='project-clone' id='<%= project_clone_id(repository.id) %>' name="project_clone" readonly="readonly" type="text" value="<%= ssh_url(repository.url) %>" autocomplete="off"/>
</div>
<p>
  <%= show_description(repository) %>
</p>
</div>

app/views/git_lab_repositories/_scripts.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'gitlab', :plugin => 'redmine_gitlab_integration' %>
    <%= stylesheet_link_tag 'flaticon', :plugin => 'redmine_gitlab_integration' %>
    <%= javascript_include_tag 'gitlab', :plugin => 'redmine_gitlab_integration' %>
    <% if User.current.logged? && (!User.current.gitlab_token || User.current.gitlab_token.empty?) %>
      <%= javascript_include_tag 'gitlab_flash', :plugin => 'redmine_gitlab_integration' %>
    <% end %>
<% end %>

app/views/git_lab_repositories/_token_form.html.erb
<p><%= form.text_field :gitlab_token, size: 30 %></p>

app/views/git_lab_repositories/index.html.erb
<div class="contextual">
  <a class="icon icon-document create-btn" ><%= t(:gitlab_create) %></a>
  <a class="icon icon-add add-btn" ><%= t(:gitlab_add) %></a>
</div>
<h2>GitLab</h2>
<a href="<%= Setting.plugin_redmine_gitlab_integration['gitlab_url'] %>" target="_blank"><h6 class=".subheader-secondary"><%= t(:gitlab_open) %></h6></a>
<%= render partial: "repository", collection: @repositories, locals: { project: @project.id } %>
<% content_for :header_tags do %>
    <%= javascript_include_tag 'repository', :plugin => 'redmine_gitlab_integration' %>
<% end %>
<% if user_has_token? && user_allowed_to_add? %>
  <div id="add-repository"><%= render partial: "add_repository", locals: { project: @project.id } %></div>
  <div id="create-repository"><%= render partial: "create_repository", locals: { project: @project.id } %></div>
<% end %>

app/views/settings/_gitlab_int_settings.html.erb
<p>
  <%= label_tag 'settings_gitlab_url', "Gitlab Url" %>
  <%= text_field_tag 'settings[gitlab_url]', settings['gitlab_url'] %>
  <br/>
  <%= label_tag 'settings_gitlab_bot', "Bot token" %>
  <%= text_field_tag 'settings[gitlab_bot]', settings['gitlab_bot'] %>
  <br/>
  <%= label_tag 'settings[gitlab_members_sync]', "Project members synchronization" %>
  <%= check_box_tag 'settings[gitlab_members_sync]', 'enabled', (settings['gitlab_members_sync'] == 'enabled') %><br/>
  <%= label_tag 'settings_gitlab_autoremove', "Autoremove repository" %>
  <%= check_box_tag 'settings[gitlab_autoremove]', 'enabled', (settings['gitlab_autoremove'] == 'enabled') %><br/>
  <% Role.select("id, name").each do |role| %>
    <%= label_tag "settings[gitlab_role][#{role.id}]", role[:name] %>
    <%= select_tag "settings[gitlab_role][#{role.id}]", options_for_select([["Reporter", 20], ["Developer", 30], ["Manager", 40], ["Owner", 50]], (settings['gitlab_role'] ? settings['gitlab_role']["#{role.id}"] : "20")) %><br/>
  <% end %>
</p>